### ISSUE TITLE
hi there need help

### ISSUE THREAD

**Issue by anantsparrow** [CZ-NIC/dns-probe#2]
hello there, i need help in installing the fred epp server on my ubuntu server

**Comment by zdenekb** [comment]
Hello, please try to follow instructions at https://fred.nic.cz/documentation/html/
Within a week we will add new installation procedure with much better installation script support. So maybe wait for it.
If you need more and deeper assistance, I would suggest to ask for any of support program, see: https://fred.nic.cz/en/support/
Kind regards,
Zdenek.

**Comment by anantsparrow** [comment]
hi, is it possible to sell 3rd level domains using this epp? just like it.com is doing?

**Comment by llhotka** [comment]
Please move your discussion to an appropriate place, such as fred-users@lists.nic.cz
